### ISSUE TITLE
Can't access CSV result file on Android

### ISSUE THREAD

**Issue by notebookcheck** [maxim-saplin/CrossPlatformDiskTest#24]
The result file is not in the easily accessible /Android/data/com.Saplin.CPDT folder or in the Downloads folder of the device. As the test file is in /data/user/0/com... I guess the result file will be there too, but that cant be accessed without root access if I am not wrong. Is there any way to access the CSV result file on Android without root?

**Comment by maxim-saplin** [comment]
You're right, files under /data/user/{AppPackageName} are not accesible to other apps except the owning app. 

Until recently /storage/emulated/0/{AppPackageName} folder was easily accessible via 3rd party folder expolrers, though it seems not the case since Android 11. /storage/emulated/0/ pointed to so called 'external sotrage' (which effectively is not any external storage such as SD card, an odd choice of names) which was just an alias to internal memory with less strict permissions.

Indeed Android app needs an extra feature to make the CSV accessible in some shared location (such as Downloads folder)... Will look into that.

**Comment by maxim-saplin** [comment]
Could you please try a new build: https://github.com/maxim-saplin/CrossPlatformDiskTest/releases/download/2.3.8/com.Saplin.CPDT.apk

 - clicking on CSV file name in expanded test results should show Share dialog and send 6 CSV files to app of interest (e.g. attach to email or upload to cloud drive).

**Comment by notebookcheck** [comment]
Works, perfect, thanks for the fast update!
 Export and direct file access tested on a Xiaomi Redmi Note 8T with MIUI 12.0.2 / Android 10.
